### ISSUE TITLE
Include database management system

### ISSUE THREAD

**Issue by t-lichtenstein** [BPChain/api-server#7]
DMBS should store data from private and public blockchains to generate statistics.

**Comment by tom-lichtenstein** [comment]
DMBS should store data from private and public blockchains to generate statistics.

**Comment by fyndalf** [comment]
@tom-lichtenstein can this be closed now?

**Comment by t-lichtenstein** [comment]
If the product owner approves this ;)

**Comment by fyndalf** [comment]
The product owner does indeed :wink:
